### ISSUE TITLE
Removing member repo creators as owners of the repository

### ISSUE THREAD

**Issue by onlyawave** [Hollywood/remove-outside-collaborators#16] opened 2018-06-05 21:47 UTC
It appears that when a team member creates a repository, they are not able to see it and need to be added by an Org owner (either individually, or a team they are a part of).  Essentially, even though they create the repository, and should be the owner, they are just having their access removed. 

I opened a Github support ticket about this issue, in hopes that it might be something else, but it looks like after adding this tool - that is the problem. 

Is this expected behavior? 

Here is the GitHub support ticket:

```Hey Andrew,

[From my original email:] "I did have to give teams he is a part of Admin access after the fact. I also thought it was worth pointing out, we added a new GitHub App last week: “Remove Outside Collaborators”. Could that have anything to do with it?"

I think this might be the culprit!

If a user creates a new private repository, they're added as a collaborator when the following default member privileges are set for an Organisation:

Default repository permission - None
Can Create Repositories - True

If the installed app is removing collaborators, it would mean removing permissions for the member who created the repository.

Hope this helps and please let me know if you need anything else!

Cheers
Stacey```

**Comment by Hollywood** [comment] 2018-06-10 16:41
Ahh @onlyawave that somewhat makes sense. Let me check it out, I’ll get back to you on this. 

/cc: @migarjo

**Comment by bennysp** [comment] 2018-06-14 20:57
@Hollywood - I just experience the very same behavior with my organization too.

**Comment by bennysp** [comment] 2018-06-14 21:02
My orgs default permission is "Read", but I don't know if that is relevant.

**Comment by Hollywood** [comment] 2018-06-15 01:50
Thanks @bennysp. I’m going to work on this tomorrow. Hopefully I’ll have a fix for you very soon. This is an interesting edge case that I admittedly haven’t thought of.

**Comment by bennysp** [comment] 2018-06-15 02:31
I really appreciate that @hollywood. This is the perfect plugin to many organizations, so solving this would be huge. 
I am happy to invest any personal time to fix, so let me know if there is anyway to help.

**Comment by onlyawave** [comment] 2018-06-15 19:49
Thanks @Hollywood !  I also might have found a pair here that can take a look at it - if they find a good workaround I'll be sure to let you know!

**Comment by Hollywood** [comment] 2018-06-26 21:01
Sorry gents, I found the issue. An `added` event gets kicked off anytime a repo is created right after the `created` event. I just need to add a check to ensure that the user is part of the org. If they are, we ignore the removal functionality.

Working on it literally right now.

@onlyawave @bennysp

**Comment by Hollywood** [comment] 2018-06-26 22:04
Something must have changed in regards to events being sent. I wanna dig into why I never once encountered this edge case. Regardless, the fix should be posted by the end of the week. 

/cc @onlyawave @bennysp

**Comment by bennysp** [comment] 2018-06-26 22:54
@Hollywood - This is great news that you found the culprit.  Thanks!

**Comment by Hollywood** [comment] 2018-06-28 01:12
@onlyawave @bennysp this should be fixed and deployed. 

Could you please test on your end when you have a few? 

My simple test case was:

- Change org permissions to `none`
- Add an individual to the org as a new user
- Create repo
- Still Admin on repo after creation

**Comment by bennysp** [comment] 2018-06-28 15:13
@Hollywood - It looks like it is fixed now!

My org is setup with `read` permissions, just to note and I confirmed that the user is still admin after the repository setup.

Thank you so much for the quick turnaround on this!

**Comment by Hollywood** [comment] 2018-06-28 16:41
Anytime @bennysp ! The issue was that after a repo is created under an org, we send a `created` event but immediately send an `added` event afterwards. The code wasn’t checking to see if the individual was a member of the organization so it assumed they were an outside collaborator. My apologies for that, I didn’t realize that `added` event was sent after a repo creation. It’s due to ownership being transferred but still allowing that member to be an admin on that repo.

**Closed** 2018-08-15 15:58 UTC
